CREATE TABLE IF NOT EXISTS "users" (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password CHAR(60) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT(CURRENT_TIMESTAMP),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT(CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS "tasks" (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description TEXT NOT NULL DEFAULT(''),
	is_completed BOOL NOT NULL DEFAULT(false),
	user_id INT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT(CURRENT_TIMESTAMP),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT(CURRENT_TIMESTAMP),

	CONSTRAINT fk_tasks_user_id FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE
);
